name: Build and Push Service Image

on:
  workflow_call:
    inputs:
      service_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
        

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ inputs.image_name }}:latest ${{ inputs.service_path }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ inputs.image_name }}:latest
      - name: Logout from Azure
        run: az logout
        if: always()
