name: Frontend CD - Deploy to AKS

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-push:
    uses: ./.github/workflows/common-steps.yml
    with:
      service: frontend
      image_tag: ${{ github.sha }}

  deploy-frontend:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Inject backend IPs into frontend config
        run: |
          sed -i 's|_PRODUCT_API_URL_|http://your-product-service-ip:8000|g' frontend/main.js
          sed -i 's|_ORDER_API_URL_|http://your-order-service-ip:8001|g' frontend/main.js

      - name: Deploy frontend to AKS
        run: |
          kubectl apply -f k8s/frontend.yaml

      - name: Azure Logout
        if: always()
        run: az logout
