# week08/.github/workflows/frontend_ci.yml

name: Frontend CI - Build & Push Image

on:
  push:
    branches: [main, development]
    paths:
      - 'backend/**'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    branches: [main, development]
    paths:
      - 'backend/**'
      - '.github/workflows/frontend_ci.yml'
  workflow_dispatch:

  # Automatically on pushes to main branch
  #push:
  #  branches:
   #   - main
   # paths: # Only trigger if changes are in the frontend directory
    #  - 'frontend/**'
    #  - '.github/workflows/frontend_ci.yml' # Trigger if this workflow file changes

# Define global environment variables that can be used across jobs
env:
  # ACR Login Server (e.g., myregistry.azurecr.io)
  # This needs to be set as a GitHub Repository Secret
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  # Dynamically generate image tags based on Git SHA and GitHub Run ID
  # This provides unique, traceable tags for each image build
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    uses: ./.github/workflows/build-and-push.yml
    with:
      service_path: ./frontend
      image_name: frontend